
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CadPasteleria
{

using System;
    using System.Collections.Generic;
    
public partial class Proveedor
{

    public int id { get; set; }

    public string NombreProveedor { get; set; }

    public string TelefonoProveedor { get; set; }

    public string EmailProveedor { get; set; }

    public string DireccionProveedor { get; set; }

    public string usuarioRegistro { get; set; }

    public System.DateTime fechaRegistro { get; set; }

    public short estado { get; set; }

}

}
